### ISSUE TITLE
pydantic error

### ISSUE THREAD

**Issue by mishima1992** [akmalharith/epg-grabber#16]
I use windows PC, using Python 3.8 - 3.11 with same error
`py-epg-cli local -f astro_com_my.json -o epg.xml
Traceback (most recent call last):
  File "C:\Users\mishima1992\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\mishima1992\AppData\Local\Programs\Python\Python39\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Users\mishima1992\AppData\Local\Programs\Python\Python39\Scripts\py-epg-cli.exe\__main__.py", line 7, in <module>
  File "C:\Users\mishima1992\AppData\Local\Programs\Python\Python39\lib\site-packages\epg_grabber\cli.py", line 94, in main
    local(args)
  File "C:\Users\mishima1992\AppData\Local\Programs\Python\Python39\lib\site-packages\epg_grabber\cli.py", line 26, in local
    input_config = InputConfig.parse_file(args.file)
  File "pydantic\main.py", line 569, in pydantic.main.BaseModel.parse_file
  File "pydantic\main.py", line 526, in pydantic.main.BaseModel.parse_obj
  File "pydantic\main.py", line 342, in pydantic.main.BaseModel.__init__
pydantic.error_wrappers.ValidationError: 1 validation error for InputConfig
configs
  field required (type=value_error.missing)`

**Comment by mishima1992** [comment]
my fault. I thought astro_com_my.json was a config file, I missed an example config file in the readme
